### PR TITLE
Connect nulls

### PR DESCRIPTION
**Pull request by mrjones-plip**
before:
image

after:
image

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@jkuester - doing a single big commit seemed to introduce a lot of changes that were hard to track - did them a bunch of smaller commits so it's easier to track deltas across the series.

**Comment by jkuester** [comment]
Those 3 doc count panels cannot be edited because they are just auto-generated repeats based on the first one.  They other three will update as soon as the dashboard is actually saved.

**Review by jkuester — APPROVED** [review]
@mrjones-plip how necessary do you feel these changes are in the event that https://github.com/medic/cht-monitoring/commit/d27e2a664827b57bd1a1f335c14c1529d7108012 has actually fixed the issue with gaps in the graph?  

image

I pushed the Prometheus scrapeInterval changes ~14:25 and you can see in the screenshot that there are not gaps after that (presumably because Prometheus is no longer deciding the time-series are stale...).  

One one hand, connecting the null values in the graphs anyway might be a nice way to future proof things.  However, if I am correct, those gaps in data are also related to the "NO DATA" issues we were having in the Stat panels, so this is part of a more general data issue at that point.  Also, connecting the null values is going to hide any situations where the actually _is no monitoring data_ (e.g. if Prometheus goes down and then comes back up, will there be a gap in the graph or will the values just get connected?)

**Comment by jkuester** [comment]
Spoke with @mrjones-plip and we decided to close this PR for now without merging since the scrapeInterval fix seems to have address the root cause of the data gaps.

**Pull request closed without merging**
