### PR TITLE
feat(#15) add config for ingesting Postgres data

### PR DESCRIPTION
**Pull request by jkuester**
- Refactors the exporters (now `json` and `postgres`) so they are nested in the `exporters` directory
  - Also extracts the Prometheus scrape_config for each exporter into the related folder.
- Adds a new Postgres exporter that supports connecting to multiple different Postgres dbs (and mapping each DB to its related CHT instance)
	- Adds 1 custom metric, `couch2pg_progress_sequence`, that is extracted via query from Postgres
	- All the actual monitoring stats from the Postgres server are also being collected by Prometheus
- Adds new "Couch2PG Backlog" panel to the "CHT Admin Overview" dashboard that shows the number of changes that need processed
	- This backlog value is calculated by taking the update sequence values from the CHT `/monitoring` metric, `cht_couchdb_update_sequence`, and subtracting the `couch2pg_progress_sequence` value from it.

This is per some of or all of #15 depending how you look at it ;)

## Usage:

You need to have access to a Postgres server populated by couch2pg.

Create config files:

```shell
cp exporters/postgres/postgres-instances.example.yml exporters/postgres/postgres-instances.yml 
cp exporters/postgres/postgres_exporter.example.yml exporters/postgres/postgres_exporter.yml
```

Add your target postgres connection URL to `postgres-instances.yml` along with the proper root url for your CHT instance as the label value.

Add a section to the `auth_modules` object in the `postgres_exporter.yml` file for your Postgres instance with the proper username and password.

Spin everything up by running (include `-f deployemnt/fake-cht/docker-compose.fake-cht.yml` if you want to start the CHT test server):

```shell
docker compose -f docker-compose.yml -f exporters/postgres/docker-compose.postgres-exporter.yml up -d
```

## Adding custom exporters

While it was not the main intent of this PR, the changes here should make it easy (and serve as a pattern) for what you would need to do to add additional Prometheus exporters to a deployment of cht-monitoring.

Just add a new folder in `./exporters` that contains your custom `docker-compose` and `scrape_config` files (modeled after the ones in `exporters/postgres` so that your `scrape_config` is mapped into the prometheus container).  Launch everything together by `-f` including your custom docker-compose file when doing the `compose up`.

Closes https://github.com/medic/cht-monitoring/issues/19

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@jkuester  - I was hoping to get to this today, but it will have to wait until tomorrow!

**Comment by mrjones-plip** [comment]
@jkuester - I tried to get this working locally and could not.  the main issue I hit was that I could never get get the `couch2pg backlog` panel to show anything by "no data found".  The second issue was that I couldn't find a way in the logs to see if the postgres instance was successfully (or unsuccessfully) being scraped by prometheus.  Let's hop on a real time call next week and figure out what I'm doing wrong!

**Review by mrjones-plip — CHANGES_REQUESTED** [review]
minor tweak before getting to real review

**Review by tatilepizs — APPROVED** [review]
It looks really good Josh, I tested it and it worked perfectly 🎉

**Comment by mrjones-plip** [comment]
sweet! I'll grab the review tomorrow (Tue)

**Review by mrjones-plip — APPROVED** [review]
love how much thought went into this PR - it works simply and works extensibly! 

:1st_place_medal:

**Comment by jkuester** [comment]
@tatilepizs @mrjones-plip Now that everyone has approved this pr, I finally got the test config done!  :facepalm: 

The usage is documented in the [development README](https://github.com/medic/cht-monitoring/pull/23/files#diff-920be6c704b383d42b553eb2b3a233dc37f9f67be14b548499837105b19f6a9c), but the TLDR is that I added some code to the fake-cht to be able to push data to a Postgres instance.  (I did check and see if there was a way to just mock/fake a whole Postgres instance. There was a few promising leads, but I could not find anything simple/maintained that would actually act as the server endpoint (which we need since that is what the exporter connects to).  Ultimately, the code is really simple to just push the data values we want into a real Postgres instance...)

**Review by mrjones-plip — APPROVED** [review]
This is brilliant! Nice work here @jkuester .  I'm going to defer to @tatilepizs  - I still can't get `fake-cht` to run (see error below), and now when I run it outside of docker it of course can resolve hosts like `postgres` outside of the docker networking environment.  I'm going to approve to unblock!

```
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /home/node/app/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/home/node/app/package-lock.json'
npm ERR!  [Error: EACCES: permission denied, open '/home/node/app/package-lock.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/home/node/app/package-lock.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /home/node/.npm/_logs/2023-04-27T00_16_23_089Z-debug-0.log
```

**Review by mrjones-plip — APPROVED** [review]
Breaking news! Worked fine on my desktop!? :shrimp: 

re-approving with this nice lil' video:


https://user-images.githubusercontent.com/8253488/234760817-86d62a75-5293-4349-ab6c-8c0638547522.mp4

**Review by tatilepizs — APPROVED** [review]
I tested it one more time and everything is working perfectly ✅ 
Reviewing the recent changes I read the [development/README.md](https://github.com/medic/cht-monitoring/tree/15_ingest_postgres_data/development#developing) for the first time and I loved this part:

> 0. Update QA with the work to be done to ensure they're informed and can guide development

Thank you for that @jkuester  🤍 

image

**Pull request merged**
